resolver: lts-7.19

extra-package-dbs: [hackage]

packages:

- location: '.'
- location:
    git: https://github.com/reflex-frp/reflex.git
    commit: a63aba90bdea5ae5b3e1506d468613bdfedcdfa3
  extra-dep: true
- location:
    git: https://github.com/Arguggi/reflex-dom.git
    commit: 767c9b7625c61208b552f64b95719edac18a6e29
  extra-dep: true
    #- location:
    #git: https://github.com/reflex-frp/reflex.git
    #commit: 63cb8f83deb68f416ba95afe3d1c5372a40dca43
    #extra-dep: true
    #- location:
    #git: https://github.com/reflex-frp/reflex-dom.git
    #commit: 957be7e0622fe79cdfb4cb4919c6a67f89a00b57
    #subdirs:
    #- reflex-dom
    #- reflex-dom-core
    #extra-dep: true
# for haddock is broken on this package on  hacage
- location:
    git: https://github.com/paolino/MemoTrie
    commit: ecb838f4afc5e01400cfc867e07f78064cf55ac4
  extra-dep: true

extra-deps:


- ghcjs-dom-0.2.4.0
- ref-tf-0.4.0.1
- zenc-0.1.1
- dependent-map-0.2.3.0
- dependent-sum-0.3.2.2
- webkitgtk3-javascriptcore-0.13.2.0
- newtype-generics-0.5
