resolver: lts-7.19

extra-package-dbs: [hackage]

packages:
- location: '.'
- location:
    git: https://github.com/reflex-frp/reflex.git
    commit: 63cb8f83deb68f416ba95afe3d1c5372a40dca43
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex-dom.git
    commit: 957be7e0622fe79cdfb4cb4919c6a67f89a00b57
  subdirs:
    - reflex-dom
    - reflex-dom-core
  extra-dep: true
# for haddock is broken on this package on  hacage
- location:
    git: https://github.com/paolino/MemoTrie
    commit: ecb838f4afc5e01400cfc867e07f78064cf55ac4
  extra-dep: true

extra-deps:

- ghcjs-dom-0.8.0.0
- jsaddle-0.8.3.2
- jsaddle-webkit2gtk-0.8.3.1
- newtype-generics-0.5
- ref-tf-0.4.0.1
- zenc-0.1.1
- prim-uniq-0.1.0.1
- ghcjs-dom-jsaddle-0.8.0.0
- gi-webkit2-4.0.12
- webkit2gtk3-javascriptcore-0.14.2.1
- jsaddle-dom-0.8.0.0
- gi-javascriptcore-4.0.12
- haskell-gi-0.20.1
- haskell-gi-base-0.20.2
- gi-gtk-3.0.14
- gi-gio-2.0.12
- gi-glib-2.0.12
- gi-gobject-2.0.12
- gi-cairo-1.0.12
- gi-atk-2.0.12
- gi-pango-1.0.12
- gi-gdkpixbuf-2.0.12
- gi-soup-2.4.12
- gi-gdk-3.0.12
